==== Exception state ====
Type: Informational
Contract: Benchmark
Function name: run(uint256)
PC address: 120
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: /home/vagrant/host/benchmarks/./assert_sym.sol:5

assert(param > 0)

--------------------


