2018-05-24 17:37:35,800: [13107] m.main:INFO: Beginning analysis
2018-05-24 17:37:36,585: [13107] m.ethereum:INFO: Starting symbolic transaction: 1
2018-05-24 17:37:36,884: [13107] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-05-24 17:37:37,975: [13107] m.c.executor:ERROR: Exception: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 481, in run
    self.generate_testcase(current_state, str(e))
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 353, in generate_testcase
    self._publish('will_generate_testcase', state, 'test', message)
  File "/usr/local/lib/python2.7/dist-packages/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/utils/event.py", line 134, in _publish_impl
    sink._publish_impl(_name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1344, in _generate_testcase_callback
    function_name, arguments = ABI.parse(signature, tx.data)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 502, in parse
    val, off = ABI._consume_type(ty, data, off)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 453, in _consume_type
    result = data[dyn_offset + 32:dyn_offset + 32 + size]
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/expression.py", line 720, in __getitem__
    size = self._get_size(index)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/expression.py", line 714, in _get_size
    assert isinstance(size, BitVecConstant)
AssertionError

2018-05-24 17:37:38,166: [13107] m.ethereum:WARNING: Integer overflow at ADD instruction
2018-05-24 17:37:38,213: [13107] m.ethereum:WARNING: Integer overflow at ADD instruction
2018-05-24 17:37:39,437: [13107] m.ethereum:WARNING: Integer overflow at ADD instruction
2018-05-24 17:37:42,452: [13107] m.ethereum:WARNING: Integer overflow at ADD instruction
2018-05-24 17:37:43,334: [13107] m.ethereum:WARNING: Integer overflow at ADD instruction
2018-05-24 17:37:43,346: [13107] m.c.executor:ERROR: Exception: __nonzero__ for Bool
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/executor.py", line 459, in run
    if not current_state.execute():
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore/platforms/evm.py", line 2217, in execute
    self.current.execute()
  File "/usr/local/lib/python2.7/dist-packages/manticore/platforms/evm.py", line 1383, in execute
    result = implementation(*arguments)
  File "/usr/local/lib/python2.7/dist-packages/manticore/platforms/evm.py", line 1647, in CALLDATACOPY
    self._consume(GCOPY * ceil32(size) // 32)
  File "/usr/local/lib/python2.7/dist-packages/manticore/platforms/evm.py", line 1331, in _consume
    assert fee >= 0
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/expression.py", line 123, in __nonzero__
    raise NotImplementedError("__nonzero__ for Bool")
NotImplementedError: __nonzero__ for Bool

2018-05-24 17:37:43,374: [13107] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-05-24 17:37:43,971: [13107] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 0% | Terminated States: 3 | Alive States: 2
2018-05-24 17:37:43,993: [13483] m.ethereum:INFO: Generated testcase No. 2 - 
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1511, in f
    self.terminate_state_id(state_id)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 864, in terminate_state_id
    self._generate_testcase_callback(state, 'test', last_exc.message)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 1344, in _generate_testcase_callback
    function_name, arguments = ABI.parse(signature, tx.data)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 502, in parse
    val, off = ABI._consume_type(ty, data, off)
  File "/usr/local/lib/python2.7/dist-packages/manticore/ethereum.py", line 453, in _consume_type
    result = data[dyn_offset + 32:dyn_offset + 32 + size]
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/expression.py", line 720, in __getitem__
    size = self._get_size(index)
  File "/usr/local/lib/python2.7/dist-packages/manticore/core/smtlib/expression.py", line 714, in _get_size
    assert isinstance(size, BitVecConstant)
AssertionError
2018-05-24 17:37:45,143: [13107] m.ethereum:INFO: Results in /home/vagrant/mcore__Ybi4M
EXITSTATUS=0
